spring.application.name=backend
# Google OAuth (rellena con tus valores o usa env vars)
google.oauth.clientId=${GOOGLE_OAUTH_CLIENT_ID:}
google.oauth.clientSecret=${GOOGLE_OAUTH_CLIENT_SECRET:}
# Para SPA recomendamos usar "postmessage" como redirect URI cuando Google devuelve code a frontend
google.oauth.redirectUri=${GOOGLE_OAUTH_REDIRECT_URI:postmessage}

# URL del frontend (para CORS)
app.frontend.origin=https://frontend-downloader.vercel.app

# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/music_downloader}
spring.datasource.username=${DATABASE_USERNAME:app}
spring.datasource.password=${DATABASE_PASSWORD:app123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Python API
python.api.url=${PYTHON_API_URL:http://localhost:8000}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
