spring.application.name=backend
# Google OAuth (rellena con tus valores o usa env vars)
google.oauth.clientId=${GOOGLE_OAUTH_CLIENT_ID:}
google.oauth.clientSecret=${GOOGLE_OAUTH_CLIENT_SECRET:}
# Para SPA recomendamos usar "postmessage" como redirect URI cuando Google devuelve code a frontend
google.oauth.redirectUri=${GOOGLE_OAUTH_REDIRECT_URI:postmessage}

# URL del frontend (para CORS)
app.frontend.origin=https://frontend-downloader.vercel.app
